from sentence_generation.Album import *
from sentence_generation.Book import *
from sentence_generation.City import *
from sentence_generation.Festival import *
from sentence_generation.FoodnDrinks import *
from sentence_generation.Movie import *
from sentence_generation.Organization import *
from sentence_generation.Paint import *
from sentence_generation.Person import *
from sentence_generation.SportsnEvents import *
from sentence_generation.University import *