from util_template.Album import *
from util_template.Book import *
from util_template.City import *
from util_template.Festival import *
from util_template.FoodnDrinks import *
from util_template.Movie import *
from util_template.Organization import *
from util_template.Paint import *
from util_template.Person import *
from util_template.SportsnEvents import *
from util_template.University import *